# Generated by Django 6.0.5 on 2026-05-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_media_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('archived', 'Archived'), ('draft', 'Draft'), ('deleted', 'Deleted')], db_index=True, default='published', max_length=10),
        ),
    ]
