# Generated by Django 6.0.5 on 2026-05-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='media',
        ),
        migrations.AddField(
            model_name='post',
            name='media_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
