# Generated by Django 6.0.5 on 2026-05-30 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_replace_media_url_with_media_key'),
        ('users', '0002_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='users.department'),
        ),
    ]
