# Generated by Django 6.0.5 on 2026-06-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_report_models'),
        ('users', '0003_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='department',
        ),
        migrations.RemoveField(
            model_name='post',
            name='minister',
        ),
        migrations.AddField(
            model_name='post',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='tagged_posts', to='users.department'),
        ),
        migrations.AddField(
            model_name='post',
            name='ministers',
            field=models.ManyToManyField(blank=True, related_name='tagged_posts', to='users.minister'),
        ),
    ]
